# This is a basic workflow to help you get started with Actions

name: CopyChangesToThemeRepo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
          chmod 777 ./dependencies/globalizeIt/GlobalizeIt.Console
          ./dependencies/globalizeIt/GlobalizeIt.Console -c ${{ github.workspace }}/tex/ -p ${{ github.workspace }}/output/tex/
      shell: bash
    - name: Copy files to another repository
      uses: crykn/copy_folder_to_another_repo_action@v1.0.6
      env:
        API_TOKEN_GITHUB: ${{ secrets.REPO_TOKEN }}
      with:
        source_folder: ./output/tex/
        destination_repo: Aspose/products.aspose.com
        destination_folder: /content/tex/
        destination_branch: main
        user_name: ${{ github.actor }}
        user_email: ${{ github.actor }}
        commit_msg: Update file(s) "./tex/" from "aspose-tex/Aspose.TeX-Products"
